#!/usr/bin/python3
from sys import argv

def factorize(value):
    index = 2

    if value < 2:
        return

    while value % index:
        index += 1
    print(f"{value:.0f}={value / index:.0f}*{index:.0f}")


if __name__ == "__main__":
	if len(argv) != 2:
		exit()

	with open(argv[1]) as file:
		line = file.readline()
		while line != "":
			value = int(line.split('\n')[0])
			factorize(value)
			line = file.readline()
